server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_ad_data?autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: introcks1234
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: 192.168.31.51:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: introcks1234
    #binlogName: binlog.000038
    position: 60451

  kafka:
    topic: ad-search-mysql-data
